package me.maploop.script;

public enum TokenType {
    FN, VAR, RETURN, IDENTIFIER, NUMBER, STRING,
    COLON, ARROW, COMMA, OPEN_PAREN, CLOSE_PAREN,
    OPEN_BRACE, CLOSE_BRACE, SYS, DOT, PRINTLN,
    EQUALS, PLUS, MINUS, MULTIPLY, DIVIDE, OPEN_BRACKET,
    CLOSE_BRACKET, EOF, SEMICOLON, POWER
}
